spring:
  profiles:
    active:
      - dog
      - EN
      - prod
arnet:
  username: ymlSuperuser
  password: ymlDbPassword
  jdbcurl: ymlSomeUrlForDataBase

---
spring:
  profile: prod
arnet:
  username: PRODuserFromYaml
  password: PRODpassFromYaml
  jdbcurl: PRODurlFromYamlForDataBase